export class property_table {
    public property_code: number;
    public property_city: string;
    public property_area: number;
    public property_zipcode: string;
    public property_street: string;
    public property_house_number: number;
    public property_entrance: string;
    public property_flat_number: number;
    public property_price: number;
    public property_floor: number;
    public property_lift: boolean;
    public property_disabled_access: boolean;
    public property_squaremeters: number;
    public property_number: string;
    public property_rooms: number;
    public property_parking: boolean;
    public property_balcony: boolean;
    public property_succa: boolean;
    public property_storage: boolean;
    public property_safe_room: boolean;
    public property_air_conditioning: boolean;
    public property_bars: boolean;
    public property_condition: number;
    public property_client_code: string;
    public property_type: number;
    public property_airways: number;
    public property_additional_information: string;
}